# blank-dev-template
# basic bootstrap template

title: CollectionBuilder
description: "CollectionBuilder is an open source tool for creating digital collection and exhibit websites that are driven by metadata and powered by modern static web technology."
# url is your gh-pages base, following the pattern: username.github.io
url: https://collectionbuilder.github.io
baseurl: /

github-organization: https://www.github.com/collectionbuilder/

# collections
collections:
  cdm:
    output: true
    permalink: /docs/:collection/:slug
    sort_by: step
  gh:
    output: true
    permalink: /docs/:collection/:slug
  sa:
    output: true
    permalink: /docs/:collection/:slug
  workshop:
    output: true
    permalink: /:collection/:title
    sort_by: step
  
# set defaults
defaults:
  - scope:
      path: ""
      type: "cdm"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "workshop"
    values:
      layout: "workshop"


# Use Bootstrap (true, false)
bootstrap: true
# Use optional Bootstrap JS (true, false)
bootstrap-js: true
# Use JQuery Core
jquery: true
# Use fontawesome CDN (true, false)
fontawesome: false
