# CollectionBuilder
# basic bootstrap template

title: CollectionBuilder
description: "CollectionBuilder is an open source tool for creating digital collection and exhibit websites that are driven by metadata and powered by modern static web technology."
# url is your gh-pages base, following the pattern: username.github.io
url: 
baseurl: 

github-organization: https://www.github.com/collectionbuilder/

featured-image: https://collectionbuilder.github.io/images/logo/cb-logo-solid-vgold-transparent.png
featured-image-alt: "CollectionBuilder bracket logo"

# collections
collections:
  docs:
    output: false
  about:
    output: false
  workshop-gh:
    output: true
    permalink: /:collection/:title
    sort_by: step
  workshop-dhsi:
    output: true
    permalink: /:collection/:title
    sort_by: step
  
# set defaults
defaults:
  - scope:
      path: ""
      type: "workshop"
    values:
      layout: "workshop"
  - scope:
      path: ""
      type: "workshop-gh"
    values:
      layout: "workshop"
  - scope:
      path: ""
      type: "workshop-dhsi"
    values:
      layout: "workshop-dhsi"

# ignore stuff
exclude: [old/, README.md, LICENSE]
