# blank-dev-template
# basic bootstrap template

title: CollectionBuilder, WTF

# url is your gh-pages base, following the pattern: username.github.io
url: https://collectionbuilder.github.io


github-organization: https://www.github.com/collectionbuilder/
collections:
  skin-contentdm:
    output: true
    permalink: /:collection/docs/:slug
  gh:
    output: true
    permalink: /:collection/docs/:slug
  sa:
    output: true
    permalink: /:collection/docs/:slug

# Use Bootstrap (true, false)
bootstrap: true
# Use optional Bootstrap JS (true, false)
bootstrap-js: true
# Use JQuery Core
jquery: true
# Use fontawesome CDN (true, false)
fontawesome: false
